
import { Note } from "../types";

/**
 * BridgeService handles high-speed communication between the web app 
 * and local agents (LLMs/scripts) running on the user's machine.
 */
export class BridgeService {
    private socket: WebSocket | null = null;
    private onMessage: (data: any) => void;
    private statusCallback: (status: 'connected' | 'disconnected' | 'connecting') => void;

    constructor(
        onMessage: (data: any) => void,
        statusCallback: (status: 'connected' | 'disconnected' | 'connecting') => void
    ) {
        this.onMessage = onMessage;
        this.statusCallback = statusCallback;
        this.initGlobalAPI();
    }

    private initGlobalAPI() {
        (window as any).cogniNotesAPI = {
            createNote: (title: string, content: string) => {
                this.onMessage({ type: 'CREATE_NOTE', title, content });
            },
            updateActiveNote: (content: string) => {
                this.onMessage({ type: 'UPDATE_NOTE', content });
            },
            getActiveNote: () => {
                const activeId = (window as any).activeNoteId;
                const notes = JSON.parse(localStorage.getItem('cogni_notes') || '[]');
                return notes.find((n: any) => n.id === activeId);
            },
            pushToTerminal: (content: string) => {
                this.sendToAgent({ type: 'EXECUTE_LOCAL', content });
            }
        };
    }

    sendToAgent(data: any) {
        if (this.socket?.readyState === WebSocket.OPEN) {
            this.socket.send(JSON.stringify(data));
        }
    }

    connect() {
        this.statusCallback('connecting');
        try {
            this.socket = new WebSocket('ws://localhost:8765');

            this.socket.onopen = () => {
                this.statusCallback('connected');
                console.log('CogniNotes: Terminal Bridge Active');
            };

            this.socket.onmessage = (event) => {
                try {
                    const data = JSON.parse(event.data);
                    this.onMessage(data);
                } catch (e) {
                    console.error('Bridge Error:', e);
                }
            };

            this.socket.onclose = () => {
                this.statusCallback('disconnected');
                setTimeout(() => this.connect(), 5000);
            };

            this.socket.onerror = () => this.socket?.close();
        } catch (e) {
            this.statusCallback('disconnected');
        }
    }

    disconnect() {
        this.socket?.close();
    }
}

// UNIVERSAL CODE AGENT RELAY (Python Implementation)
// Updated to handle note-to-terminal push events.
export const PYTHON_BRIDGE_CODE = `
import asyncio
import websockets
import json
import os

# REQUIREMENTS: 
# pip install websockets

# This script is a UNIVERSAL BRIDGE. 
# 1. It sends local AI code snippets to CogniNotes.
# 2. It receives notes/code from CogniNotes and displays them locally.

async def agent_loop(websocket):
    print("--- CogniNotes Universal Terminal Bridge ---")
    print("Bridge is active. Press Ctrl+C to stop.")
    
    try:
        async for message in websocket:
            data = json.loads(message)
            
            # HANDLE INCOMING TEXT FROM COGNINOTES
            if data.get('type') == 'EXECUTE_LOCAL':
                content = data.get('content', '')
                print("\\n" + "="*40)
                print("[RECEIVED FROM COGNINOTES]")
                print("-"*40)
                print(content)
                print("="*40)
                
                # INTEGRATION TIP:
                # To auto-pipe to Ollama:
                # os.system(f"ollama run llama3 'Explain this: {content}'")
                
                # To auto-run as a script (CAUTION!):
                # with open('temp_script.py', 'w') as f: f.write(content)
                # os.system('python temp_script.py')
                
                continue

            if data.get('type') == 'CONTEXT_SYNC':
                continue

            # VOICE-TO-CODE TRIGGER
            print("\\n[Awaiting Voice Command / Input]")
            voice_command = input("Command (e.g. 'C++ hello world'): ")
            
            lang = "python"
            if "c++" in voice_command.lower(): lang = "cpp"
            elif "c" in voice_command.lower(): lang = "c"
            elif "java" in voice_command.lower(): lang = "java"
            
            content = f"\\n\\n### Voice-to-Code: {voice_command}\\n\`\`\`{lang}\\n// Generated by Local Agent\\n\`\`\`"
            
            await websocket.send(json.dumps({
                "type": "UPDATE_NOTE",
                "append": True,
                "content": content
            }))
            
    except websockets.exceptions.ConnectionClosed:
        print("Connection closed by app.")
    except Exception as e:
        print(f"Bridge error: {e}")

async def main():
    async with websockets.serve(agent_loop, "localhost", 8765):
        await asyncio.Future()

if __name__ == "__main__":
    asyncio.run(main())
`;
